sudo: required

language: go

go:
  - 1.8
  - 1.9

env:
  matrix:
  - MONGODB_HOST=mongodb://localhost
  - MONGODB_HOST=localhost

services:
  - docker
  - mongodb
  
before_install:
    - go get -v github.com/tomaszheflik/vectors

script:
    - go test
    - go run main.go
    - go build -o mdb_tester


after_success:
    - chmod a+x ./test.sh
    - ./test.sh
    - docker build -t heflik/mongo_tester .
    - docker images
    - docker run -it heflik/mongo_tester
