sudo: required

language: go

go:
  - 1.8

env:
  matrix:
  - MONGODB_HOST=mongodb://localhost
  - MONGODB_HOST=localhost

services:
  - mongodb
  - docker

before_install:
    - go get -v github.com/tomaszheflik/vectors

script:
    - go test
    - go run main.go
    - go build -o mdb_tester

after_success:
  - docker build -t heflik/mongo_tester .
  - docker images
  - docker run -it heflik/mongo_tester
