language: go

go:
  - 1.8
  - 1.9

env:
  - MONGODB_HOST=mongodb://localhost
services: mongodb

before_install:
    - go get -v github.com/tomaszheflik/vectors

script:
    - go test
    - go run main.go