sudo: required

language: go

go:
  - 1.8
  - 1.9

addons:
  hosts:
    - local.dev
env:
  matrix:
  - MONGODB_HOST=mongodb://localhost
  - MONGODB_HOST=mongodb://local.dev

services:
  - docker
  - mongodb

before_install:
    - go get -v github.com/tomaszheflik/vectors

script:
    - go test
    - go run main.go
    - go build -o mdb_tester

after_success:
    - chmod a+x ./test.sh
    - ./test.sh
    - docker run -d -p 28000:27017 --name mongo mongo
    - docker build -t heflik/mongo_tester .
    - docker images
    - docker ps
    - docker run -it -e MONGODB_HOST="mongo:28000" heflik/mongo_tester
