sudo: required

language: go

go:
  - 1.8
  - 1.9

addons:
  hosts:
    - local.dev
#env:
#  matrix:
#  - MONGODB_HOST=mongodb://localhost
#  - MONGODB_HOST=local.dev

services:
  - docker
  - mongodb

before_install:
    - go get -v github.com/tomaszheflik/vectors
    - chmod a+x ./test.sh
    - ./test.sh

script:
    - go test
    - go run main.go
    - go build -o mdb_tester


after_success:
    - docker build -t heflik/mongo_tester .
    - docker images
    - docker run -it -e MONGODB_HOST=$MONGODB_HOST heflik/mongo_tester
