# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
#version: 2
#
#jobs:
#  build:
#    docker:
#
#      # specify the version
#      - image: circleci/golang:1.8
#        working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
#        environment:
#          - MONGODB_HOST: "localhost"
#        steps:
#          - checkout
#          - run: go get -v -t -d ./...
#          - run: go test -v ./...
#          - run: go run main.go


version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

      - image: mongo:2.6.8
        command: [mongod, --smallfiles]
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go run main.go
